🐛 FIX: Align classic editor images correctly (#160)
WordPress/twentytwentyone pull request #162
Opened 2020-09-28 11:12 UTC by nielslange

Fixes #160 

<table>
<tr>
<td>Before:
<br><br>

![#160-before](https://user-images.githubusercontent.com/3323310/94425348-fec58d00-01b5-11eb-86c9-8d22fff1f2e7.png)
</td>
<td>After:
<br><br>

![#160-after](https://user-images.githubusercontent.com/3323310/94425338-fa996f80-01b5-11eb-9a6f-ac333d924e10.png)
</td>
</tr>
</table>

2020-09-29 12:34 UTC, carolinan commented
This works, but I am confused about why the IE style is not updated?

2020-09-29 23:26 UTC, nielslange commented
> This works, but I am confused about why the IE style is not updated?

I just ran `npm run build` again and now I'm seeing the changes in `ie.css` as well. I might have missed that entry before.

2020-09-30 12:28 UTC, kjellr requested changes
This works just fine, but I have just a couple organizational notes: 

If the goal is to ensure we're targeting classic editor images, we should probably narrow the scope of this rule a little bit. Maybe we target something like the `entry-content` class, rather than the `main` element? And we do that, I'd recommend placing the rule either in the `04-elements/media.scss` or `06-components/entry.scss` files instead.

2020-09-30 15:49 UTC, nielslange commented
> This works just fine, but I have just a couple organizational notes:
> 
> If the goal is to ensure we're targeting classic editor images, we should probably narrow the scope of this rule a little bit. Maybe we target something like the `entry-content` class, rather than the `main` element? And we do that, I'd recommend placing the rule either in the `04-elements/media.scss` or `06-components/entry.scss` files instead.

Thanks for your review, @kjellr.  As I'm not very familiar with the underlying SCSS structure of the Seedlet theme, which file would you recommend `04-elements/media.scss` or `06-components/entry.scss`? Given that the change affects images, I tend to move the changes to `04-elements/media.scss`.

2020-09-30 16:00 UTC, kjellr commented
Yeah, I think `media.scss` makes the most sense. 👍 Thanks @nielslange!

2020-09-30 16:46 UTC, nielslange commented
> Yeah, I think `media.scss` makes the most sense. 👍 Thanks @nielslange!

Thank you for your prompt reply, @kjellr. I moved the code as discussed. Feel free to run another review.

2020-09-30 19:15 UTC, kjellr approved these changes
Thanks!

2020-09-30 19:15 UTC, merged