🐛 FIX: Adjust READ MORE button (#206)
WordPress/twentytwentyone pull request #210
Opened 2020-10-01 13:09 UTC by nielslange

Fixes: #206 

<table>
<tr>
<td>Before:
<br><br>

![#206-before](https://user-images.githubusercontent.com/3323310/94812883-85ca6d80-0421-11eb-853c-0c726f6eeadb.png)
</td>
<td>After:
<br><br>

![#206-after](https://user-images.githubusercontent.com/3323310/94812886-87943100-0421-11eb-9847-a758a6b6be3b.png)
</td>
</tr>
</table>

 **Note**

I removed `&hellip;` from the template as the ellipses as it was defined outside the READ MORE element which make positioning impossible and as it can easily be added by overwriting the translation, if needed.

2020-10-01 18:17 UTC, melchoyce commented
Thanks Niels, can you update this to match the [mockup in Figma](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=363%3A0)?

![image](https://user-images.githubusercontent.com/2846578/94847585-c8c01d00-03f0-11eb-8f57-5b4927d9cb3f.png)

2020-10-02 06:40 UTC, nielslange commented
> Thanks Niels, can you update this to match the [mockup in Figma](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=363%3A0)?

Sure. I'll do that, @melchoyce. Thanks for attaching the correct design.

2020-10-02 07:34 UTC, nielslange commented
<table>
<tr>
<td>Before:
<br><br>

![#206-before](https://user-images.githubusercontent.com/3323310/94898396-b4952200-04bb-11eb-87d1-192ebf8afd8e.png)
</td>
<td>After:
<br><br>

![#206-after](https://user-images.githubusercontent.com/3323310/94898415-bc54c680-04bb-11eb-8b37-c04f9e82bc46.png)
</td>
</tr>
</table>

@melchoyce & @carolinan To append the `READ MORE` link to the post, I had to use JS. Given that this `READ MORE` comes from Gutenberg, which requires JS to be activated, I consider the risk very low. What are your thoughts here?

2020-10-02 12:40 UTC, carolinan commented
Is it possible to do by filtering `the_content_more_link` ?
https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwenty/functions.php#L571

2020-10-02 12:46 UTC, nielslange commented
> Is it possible to do by filtering `the_content_more_link` ?
> https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwenty/functions.php#L571

Looks like it's possible. Thanks for pointing out that link, @carolinan. While my JS-based implementation works, I'm not 100% happy with it.

2020-10-02 19:40 UTC, luminuu commented
Just throwing my 2 cents in here, I'm not sure if we should go with placing items via JavaScript to another position just to match the design. If we want the theme to be a learning place for unexperienced designers and developers, I'd rather prefer the design to be slightly different than using JS in here. I'd go with Nils first iteration of the fix.

2020-10-02 20:14 UTC, melchoyce commented
If we can position it using the function @carolinan mentioned, that would be awesome. If not, I agree with @luminuu — I'd rather the theme be straight-forward and easy to understand above all else.

2020-10-02 20:18 UTC, nielslange commented
> Just throwing my 2 cents in here, I'm not sure if we should go with placing items via JavaScript to another position just to match the design. If we want the theme to be a learning place for unexperienced designers and developers, I'd rather prefer the design to be slightly different than using JS in here. I'd go with Nils first iteration of the fix.

I know exactly what you mean, @luminuu. Let me try the approach @carolinan mentioned in https://github.com/WordPress/twentytwentyone/pull/210#issuecomment-702711256. It might be possible implementing @melchoyce's design without the need of a JS fallback. Otherwise, let's use the first draft of this PR (as @melchoyce already gave her blessing to that, while I was busy crafting this reply). 😀

2020-10-03 13:54 UTC, luminuu commented
@nielslange Just noticed while testing, when hovering the read more link, the `text-decoration` is `none` instead of `dotted`, so it doesn't match the default links. Can you also fix that?

2020-10-08 06:14 UTC, aristath requested changes

2020-10-08 06:14 UTC, aristath commented on assets/js/more-link.js
> +	var links = document.querySelectorAll('.more');
Can we follow the WP coding standards here?

```suggestion
	var links = document.querySelectorAll( '.more' );
```

2020-10-08 06:14 UTC, aristath commented on assets/js/more-link.js
> +	} );
We don't have babel and we need to support IE11

```suggestion
	links.forEach( function( link ) {
		var post = link.previousElementSibling;
		post.appendChild(link);
	} );
```

2020-10-08 06:42 UTC, carolinan commented
Let's try using the filter solution instead of resolving the current JS problems.

2020-10-08 06:42 UTC, closed without merging

2020-10-08 11:38 UTC, nielslange commented
> Let's try using the filter solution instead of resolving the current JS problems.

The filter function will not lead to the expected result, as the READ MORE block is not part of the excerpt. Without JS, only the first solution as pointed out in https://github.com/WordPress/twentytwentyone/pull/210#issue-496246647 is possible.

2020-10-08 11:50 UTC, rolf-yoast commented
I agree with @nielslange. The filter can only be used to edit the html of the READ MORE block and is already applied on it in inc/template-functions.php

2020-10-08 14:13 UTC, carolinan commented
With this, we have been left with the only option which is to not follow the design for this block.

2020-10-08 14:22 UTC, melchoyce commented
Read More on a new line is okay with me, since we can't easily append it to the end of the excerpt. I think more important for the theme to be understandable.

2020-10-08 15:20 UTC, nielslange commented
@carolinan Can you open this PR again, so that I can push the first version I created?

2020-10-08 19:56 UTC, carolinan commented
@nielslange It is already worked on in a different pull request.
It is my fault for not pinging you but because there was no updates for 5 days and because beta 1 is coming closer I did not think we had the time to wait any longer.