Add customizer option for footer-copyright
WordPress/twentytwentyone pull request #408
Opened 2020-10-12 11:04 UTC by aristath

Fixes #401 

## Summary
Adds a new customizer option for the footer-copyright text and removes the copyright disclaimer & date.

## Relevant technical choices:
I opted for a new function to get the footer-copyright content. This way we can use that function both to render the content, and as a callback for the partial-refresh in the customizer setting.

## Test instructions

This PR can be tested by following these steps:
1. Go to the customizer > Theme Settings
2. Change the footer copyright text
3. Save and confirm everything works both in the customizer and on the frontent.

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

2020-10-12 11:40 UTC, carolinan commented
Code looks OK, but I don't want to make the decision alone, we can bring this up in todays meeting, because as a squad we have tried to use as few customizer options as possible.

2020-10-12 11:45 UTC, aristath commented
It could also be a PHP filter instead of an option...

2020-10-12 16:16 UTC, melchoyce commented
Yeah, I'd prefer if this wasn't an a Customizer option — especially not one that requires someone to enter HTML into a textarea. I think we should automate this:

> ©[Year] [Site Name]. Proudly Powered by [WordPress](https://wordpress.org/).

2020-10-12 16:17 UTC, melchoyce requested changes
Let's remove the Customizer option.

2020-10-12 21:16 UTC, carolinan commented
But the year is the root of the problem and it was agreed on during the meeting that we would use the customizer option?

2020-10-12 21:35 UTC, melchoyce commented
I had a quit chat with @carolinan and it sounds like we've had a misunderstanding. Let's talk more about this, so I can understand better. What's the problem we're having with displaying the year?

2020-10-12 22:03 UTC, pattonwebz commented
Most often we see something like `2002-2020` where people indicate the age and copyright timeframe of the site and it's contents. Having it autogenerate the copyright with just the current year is probably not sufficient for a good portion of the potential user; hence the need for an input to set it.

2020-10-13 04:56 UTC, aristath commented
> especially not one that requires someone to enter HTML into a textarea

I agree that HTML in a textarea looks a bit funky. But there is no other way to actually have links... If we want `WordPress` to link to w.org then they need to be able to add the link somehow, which is why in this PR I did it with a textarea/HTML

2020-10-13 07:30 UTC, carolinan commented
What if we left the org link (imprint) out of it (left it as it is right now), and only had a simple text field for the users copyright text.
The field would _allow_ basic HTML like a link or bold text, but it would not be _needed._

If they want to write "Copyright 2002-2020" in plain text they can, if they want to write "This site uses cookies", or link to the privacy policy, they can do that too.

2020-10-13 08:23 UTC, aristath commented
We could also just replace `WordPress` in the text with `<a href="https://w.org">WordPress</a>`...

2020-10-13 13:31 UTC, melchoyce commented
Just had a quick chat with @kjellr about this. What if we instead recommended that folks use a text widget to add copyright information, if they need it (we can demo this on https://2021.wordpress.net/), and then had a static "Proudly powered by [WordPress](https://wordpress.org/)" line that developers building sites for clients could filter out or whatever if needed? That would match Twenty Nineteen, Seventeen, etc. 

This way, if folks need formatting, the text widget will allow them to add this without HTML. If they need something really custom, they can use an HTML widget, which has some basic validation that will alert them to things like missing closing brackets.

2020-10-13 13:36 UTC, aristath commented
Hmmm So basically add a new widget-area for the footer-right, and if there are no widgets in it then show the hardcoded "powered by" string?
It could work...

2020-10-13 13:43 UTC, melchoyce commented
I'm thinking we don't even add anything new, just recommend people using the existing widget area in the footer. (So essentially, just get rid of the copyright as an explicit theme feature and leave it to site builders to include it if they want)

2020-10-13 13:50 UTC, aristath commented
I don't understand how that would work...

Currently the footer looks like this:

![Screenshot_2020-10-13 My Blog(5)](https://user-images.githubusercontent.com/588688/95869366-f3f12780-0d73-11eb-8078-72a21d4fc7b0.png)


So we've got the widget-area, followed by the footer nav, then a horizontal line, then below that we've got the logo and the copyright.
If we don't add a new widget area, then the copyright will be above the horizontal line & footer-nav :thinking:

2020-10-13 13:59 UTC, melchoyce commented
Yes, but it's an optional feature. If we can't automate it, we may as well take the simplest approach, IMO.

2020-10-13 14:03 UTC, aristath commented
So should we also remove the footer logo etc? Basically everything below the horizontal line goes bye-bye? Or should we leave it in and just center the logo?

2020-10-13 14:06 UTC, kjellr commented
Yeah, I think we should just look to what the other twenty- themes do here: Allow the the footer credit note to be filterable, and then let it be. No need to make this complicated. 

I think what Mel's suggesting is that folks can just use a text widget in the normal footer widgets area if they need to add a copyright (and can't filter the footer credit line). It's not the 100% ideal solution for this use case, but it's alright. 

In general, I personally think there are more pressing tasks to work on, and I don't think we should spend too much time figuring this out at the moment.

2020-10-13 14:17 UTC, melchoyce commented
Quick visual example:

![image](https://user-images.githubusercontent.com/2846578/95872814-3b0ff600-0d3d-11eb-9525-eddf9671d512.png)

2020-10-13 14:27 UTC, aristath commented
@melchoyce so if I understand correctly, I'm closing this PR and just changing the string in the copyright notice (remove the copyright date)

2020-10-13 15:26 UTC, melchoyce commented
Yup! Sound okay?

2020-10-13 15:28 UTC, aristath commented
Yes, sounds good. I'll take care of it tomorrow my morning :+1:

2020-10-14 06:16 UTC, aristath commented
Closing this one, replaced by https://github.com/WordPress/twentytwentyone/pull/459

2020-10-14 06:16 UTC, closed without merging