exclude .skip-link from .site a:focus
WordPress/twentytwentyone pull request #496
Opened 2020-10-15 08:54 UTC by SResok

Fixes #467 

## Summary

exclude .skip-link from .site a:focus
wrapped the .site a:focus css rules with a :not pseudo-class 

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

2020-10-15 09:12 UTC, rolf-yoast commented
CR 👍

2020-10-15 12:26 UTC, aristath requested changes

2020-10-15 12:26 UTC, aristath commented on assets/sass/04-elements/links.scss
> +	&:not(.skip-link) {
This would increase the specificity of all `a:focus` styles...
Could we instead add an override for the skip-link?

2020-10-15 13:49 UTC, SResok commented
Override outline style for the `skip-link`.
Used the same outline style as the `screen-reader-shortcut` in the wp-admin dashboard

2020-10-15 14:52 UTC, aristath approved these changes
Thank you! LGTM :+1:

2020-10-16 02:45 UTC, carolinan commented
It doesn't look exactly like the other skip links, but the rectangular shape that was inherited, has been removed.

2020-10-16 02:45 UTC, merged