Improve UI of password protected posts
WordPress/twentytwentyone pull request #523
Opened 2020-10-16 06:27 UTC by kishanjasani

Fixes: #515 

## Summary
Wider input field to match other text inputs in the theme.
Updated copy: This content is password protected. Please enter a password to view.
Remove the `:` from the password form label to match other form labels in the theme.
Use the same spacing between the input field and button as the other forms in the theme.

## Screenshots

![screenshot-twentyone local-2020 10 16-11_56_41](https://user-images.githubusercontent.com/25550562/96220630-b1636100-0fa6-11eb-99ce-443b14810bcf.png)

If this is a visual change please include screenshots of the change at various screen sizes.

2020-10-16 17:46 UTC, melchoyce requested changes
Thanks @kishanjasani! 

The form label needs to be 500 instead of 400, but investigating, it looks like we have two form weight variables:

`var(--form--label-weight)`: 400
`var(--form--label-weight-strong)`: 500

So I’m going to fix this outside of your PR. 

The only thing in your PR that needs to be updated is the font size of “This content is password protected...”. It should use `var(--global--font-size-lg)`. That's all I found, though :)

2020-10-16 19:16 UTC, melchoyce commented
Label weight fixed in #556.

2020-10-17 06:12 UTC, kishanjasani commented
Thanks @melchoyce.  I have increased the font size of the message. :+1:

2020-10-18 20:29 UTC, melchoyce approved these changes
LGTM 👍

2020-10-19 04:09 UTC, aristath approved these changes

2020-10-19 04:09 UTC, merged