Improve styling of the <fieldset> element
WordPress/twentytwentyone pull request #584
Opened 2020-10-19 08:50 UTC by JustinyAhin

Fixes #565.

## Summary
Improve styling of the <fieldset> element.

## Relevant technical choices:
No.

## Test instructions

This PR can be tested by following these steps:

1. In a new post, add a custom HTML block with a fieldset tag and input fields
2. Look how it render on frontend

## Screenshots
Before:
![Screenshot_2020-10-19 #565 – trunk wordpress test(2)](https://user-images.githubusercontent.com/33403964/96422773-5e7cea00-11f0-11eb-9251-f8027ccfaf5e.png)

After
![Screenshot_2020-10-19 #565 – trunk wordpress test(1)](https://user-images.githubusercontent.com/33403964/96422797-65a3f800-11f0-11eb-8d50-8801e7d610c9.png)

## Quality assurance
* [x] I have thought about any security implications this code might add.
* [x] I have checked that this code doesn't impact performance (greatly).
* [x] I have tested this code to the best of my abilities
* [x] I have checked that this code does not affect the accessibility negatively

2020-10-19 09:48 UTC, rolf-yoast commented
CR 👍

2020-10-19 09:52 UTC, aristath approved these changes
LGTM :+1:

2020-10-19 09:55 UTC, carolinan commented
> What if we make these fields design consistent with the comment form @carolinan?

I agree with the spacing added in the PR, it improves the usability of the fields, but it needs design feedback before merged.

2020-10-19 14:46 UTC, melchoyce commented
Adding a mockup asap

2020-10-19 14:51 UTC, melchoyce commented
Styled like comment forms, with a 1px border:

![image](https://user-images.githubusercontent.com/2846578/96467526-01396680-11f9-11eb-8a83-cad0819aa484.png)

2020-10-19 14:52 UTC, melchoyce commented
The fieldset legend is 24px.

2020-10-19 17:40 UTC, JustinyAhin commented
@melchoyce new implementation commit just sent.

![Screenshot_2020-10-19 #565 – trunk wordpress test(3)](https://user-images.githubusercontent.com/33403964/96491754-8db84900-123a-11eb-9cfc-20cb27584109.png)

2020-10-19 17:41 UTC, JustinyAhin commented
I don't think the legend can be moved inside the form frame.

2020-10-19 22:32 UTC, ryelle requested changes
Radio & checkbox inputs look misaligned now:

<img width="657" alt="Screen Shot 2020-10-19 at 6 26 32 PM" src="https://user-images.githubusercontent.com/541093/96518302-9dcf2900-1238-11eb-9c50-4ebf8e959d35.png">

Inputs outside of a fieldset are also misaligned, but that could be considered out of scope for the PR.

<img width="655" alt="Screen Shot 2020-10-19 at 6 32 25 PM" src="https://user-images.githubusercontent.com/541093/96518702-70cf4600-1239-11eb-9970-2a36d534243c.png">

2020-10-20 07:12 UTC, JustinyAhin commented
> Radio & checkbox inputs look misaligned now:

@ryelle the best workaround I found to make this works without breaking the alignment of other inputs types is to remove the margin between a radio/checkbox input and add it after the label.

![Screenshot_2020-10-20 #565 – trunk wordpress test(1)](https://user-images.githubusercontent.com/33403964/96552534-c80dfe80-12ab-11eb-8175-de67dfc259f9.png)

2020-10-20 07:24 UTC, carolinan commented
A problem I ran into is that for random forms we don't know if there is a label, or if it is before or after the radio/checkbox.

2020-10-21 15:14 UTC, hedgefield commented
Great improvements so far! I agree it would be nice if the checkbox and the label (if any) would be on the same line, but I discussed it more with @carolinan and @aristath and seems like there are so many ways of formatting the HTML of such checkboxes/radio buttons that it's almost impossible to cover all the different styling cases, and we agreed that is best left up to the plugins, since they're the ones responsible for adding those extra controls. With that, I think this one can move forward? Great job @JustinyAhin

2020-10-21 17:08 UTC, melchoyce commented
> With that, I think this one can move forward?

I think so! Updated design looks good, thanks @JustinyAhin.

Do we need one final code review?

2020-10-21 17:13 UTC, melchoyce commented
Actually one quick design note — can we make sure the font-weight for labels is `500`? I can't tell from the screenshot.

2020-10-21 17:52 UTC, JustinyAhin commented
> Actually one quick design note — can we make sure the font-weight for labels is `500`? I can't tell from the screenshot.

Yeah font-weight of labels is at 500.

2020-10-21 17:53 UTC, JustinyAhin commented
@melchoyce  @aristath I think it is good to go.

2020-10-21 18:51 UTC, ryelle approved these changes
It sounds like this is good to merge.

I'm a little concerned the `display: grid` on the fieldset could be an issue with other plugins, but we can watch for that during beta & iterate if needed.

2020-10-21 19:05 UTC, merged